site_name: Icecap Documentation
theme:
  name: material
  features:
  - navigation.footer
  - navigation.instant.preview
  - navigation.path
  - navigation.tabs
  - navigation.tabs.sticky
  - navigation.top
  - content.code.annotate
  - content.code.copy
  - content.tooltips
  palette:
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
repo_url: https://github.com/mora9715/icecap

plugins:
- search
- mkdocstrings:
    handlers:
      python:
        inventories:
        - https://docs.python.org/3/objects.inv
        - https://mkdocstrings.github.io/autorefs/objects.inv
        - https://www.mkdocs.org/objects.inv
        - https://python-markdown.github.io/objects.inv
        - https://jinja.palletsprojects.com/en/stable/objects.inv
        - https://markupsafe.palletsprojects.com/en/stable/objects.inv
        options:
          docstring_options:
            ignore_init_summary: true
          docstring_section_style: list
          filters: ["!^_"]
          heading_level: 2
          inherited_members: true
          merge_init_into_class: true
          parameter_headings: true
          separate_signature: true
          show_root_heading: true
          show_root_full_path: true
          show_signature_annotations: true
          show_inheritance_diagram: true
          show_source: true
          show_bases: true
          show_symbol_type_heading: true
          show_symbol_type_toc: true
          signature_crossrefs: true
          summary:
            classes: true
          unwrap_annotated: true

          show_docstring_attributes: true
          docstring_style: google

          line_length: 88

nav:
  - Icecap Documentation: index.md
  - Getting Started: getting_started.md
  - Tutorials:
      - Index: tutorials/index.md
      - Assets:
          - Work with MPQ files: tutorials/assets/work_with_mpq.md
          - Work with DBC files: tutorials/assets/work_with_dbc.md
      - Navigation:
          - Work with Minimap: tutorials/navigation/work_with_minimap.md
      - Communication:
          - Interact with the icecap agent: tutorials/communication/interact_with_agent.md
  - API Reference:
     - API Overview: api/index.md
     - Infrastructure:
        - Communication: api/infrastructure/communication.md
        - Driver: api/infrastructure/driver.md
        - Memory Manager: api/infrastructure/memory_manager.md
        - Name Resolver: api/infrastructure/name_resolver.md
        - Process: api/infrastructure/process.md
        - Repository: api/infrastructure/repository.md
        - Resource: api/infrastructure/resource.md
     - Domain:
        - Models: api/domain/models.md
        - DTO: api/domain/dto.md
        - Enums: api/domain/enums.md
     - Services: 
        - Overview: api/services.md
        - Navigation:
           - Minimap: api/services/navigation/minimap.md

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
extra:
  generator: false
